// Generated by Wrangler by running `wrangler types`

interface Env {
  CF_MODELS: KVNamespace;
  SYNC_TOKEN: string;
  TURNSTILE_DEV_SECRET_KEY: string;
  TURNSTILE_PROD_SECRET_KEY: string;
  IS_DEV: string;
  AI: Ai;
  ENQUIRY_JEEVA_RUBBER: KVNamespace;
}
